### ISSUE TITLE
Support for ESMF Format offline weights

### ISSUE THREAD

**Issue by hdyson** [SciTools/iris-esmf-regrid#315]
## ✨ Feature Request
It would be great if iris-esmf-regrid supported weight files generated offline.

## Motivation
We have requirements to regrid high resolution source data to UGrid meshes.  The weight generation for this is expensive (e.g. orography source data regrid to C768 on Jasmin required 550Gb RAM for 8 hours).  It would be fantastic if we could perform this weights generation step once, and store the weights for future use.

In addition, by using the ESMF weights file format (or another "standard" weights file format), we get the opportunity to use weight files generated by other tools for e.g. consistency with other processing.

## Additional context

ESMF weight file format is currently documented here: http://earthsystemmodeling.org/docs/release/ESMF_8_3_0/ESMF_refdoc/node3.html#sec:weightfileformat  They are quite aggressive at deleting old versions of docs when new versions of ESMF are released, though, so that link will not be valid indefinitely.

**Comment by trexfeathers** [comment]
Perhaps the simplest thing would be to write a converter to work with the existing [`io`](https://github.com/SciTools-incubator/iris-esmf-regrid/blob/main/esmf_regrid/experimental/io.py) module, which would avoid us needing to write any further ingestion code.

**Comment by hdyson** [comment]
Sounds good to me.  👍  I was in a meeting yesterday with @stephenworsley and got the impression that iris-esmf-regrid did not have support for offline weights.  If the solution is to have a standalone format converter, or to extend the `io` module, then I think we have a pathway that works for us.

**Comment by trexfeathers** [comment]
I didn't mean to close this though! We'll still need to work on the converter
