### ISSUE TITLE
Move to SciTools

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris-esmf-regrid#332]
## ✨ Feature Request

Move iris-esmf-regrid from SciTools-incubator to SciTools

## Motivation

SciTools-incubator is only intended for new ideas, rather than something that is being used, and actively developed by the whole team. Moving would send a clearer message to users, and make various organisation-wide admin easier.

## To do

- [x] Experiment with dummy repo to ensure the following steps will work.
- [x] Create and review PR to change references in code to new url, DO NOT MERGE YET. - #417
- [x] Create and review PR in condaforge, change url, bump build number, DO NOT MERGE YET. - https://github.com/conda-forge/iris-esmf-regrid-feedstock/pull/17
- [x] Generate new secrets where possible and appropriate (PyPi, codecov).
- [x] Make a note of current PRs, issues, discussions, projects, tags, branches Teams etc. 
- [x] Transfer ownership via settings.
- [x] Merge PRs.
- [x] Recreate appropriate secrets.
- [x] Register with appropriate services (e.g. check: codecov, pre-commit, readthedocs, zenodo).
- [x] Fix zenodo. #321
- [x] Register repo with SciTools github app.
- [x] Ensure all PRs, issues, discussions, projects, tags, branches, teams etc. are present in the new location. 
- [x] Ensure links to the old repo redirect correctly.
- [x] Run workflows to test everything's working.

**Comment by stephenworsley** [comment]
Much of this was handled by GitHub automatically, special attention was required to handle Teams, Projects, readthedocs and Apps.
