### ISSUE TITLE
Unpin conda for benchmarks when asv gets fixed

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris-esmf-regrid#354]
## 📰 Custom Issue

Currently, conda needs to be pinned to get asv to work. This happens here: https://github.com/SciTools-incubator/iris-esmf-regrid/blob/7696d493215db7bdbc061c1be3682c505d9b4a03/noxfile.py#L373

When this asv issue gets fixed, this line should be removed: https://github.com/airspeed-velocity/asv/issues/1396

**Comment by ESadek-MO** [comment]
closed by #361
